# Generated by Django 4.2.5 on 2023-11-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=25)),
                ('car_type', models.CharField(default='car', max_length=25, null=True)),
                ('manufacturer', models.CharField(default=None, max_length=25, null=True)),
                ('engine_liter', models.CharField(blank=True, default='car', max_length=10, null=True)),
                ('fuel', models.CharField(blank=True, default='car', max_length=15, null=True)),
                ('airbags', models.CharField(blank=True, default='car', max_length=3, null=True)),
                ('ground_clearance', models.CharField(blank=True, default='car', max_length=10, null=True)),
                ('ncap_rating', models.CharField(blank=True, default='car', max_length=3, null=True)),
                ('transmission', models.CharField(blank=True, default='car', max_length=20, null=True)),
                ('mileage', models.CharField(blank=True, default='car', max_length=15, null=True)),
                ('boot_space', models.CharField(blank=True, default='car', max_length=10, null=True)),
                ('fuel_tank', models.CharField(blank=True, default='car', max_length=5, null=True)),
                ('adas_level', models.CharField(blank=True, default='car', max_length=5, null=True)),
                ('dashboard', models.CharField(blank=True, default='car', max_length=10, null=True)),
                ('ventilated_seats', models.CharField(blank=True, default='car', max_length=10, null=True)),
            ],
        ),
    ]
