# Generated by Django 4.2.5 on 2023-12-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carcompare', '0004_remove_car_car_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(blank=True, default='car', max_length=30, null=True),
        ),
    ]
