# Generated by Django 4.2.5 on 2023-12-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carcompare', '0005_car_car_type_alter_car_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='airbags',
            field=models.CharField(blank=True, default='car', max_length=20, null=True),
        ),
    ]
