# Generated by Django 4.2.5 on 2024-02-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carcompare', '0006_alter_car_airbags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='ventilated_seats',
            field=models.CharField(blank=True, default='car', max_length=20, null=True),
        ),
    ]
