# Generated by Django 4.2.5 on 2024-03-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carcompare', '0007_alter_car_ventilated_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(blank=True, default='car', max_length=100, null=True),
        ),
    ]
