# Generated by Django 4.2.5 on 2024-03-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carcompare', '0008_alter_car_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_name',
            field=models.CharField(max_length=100),
        ),
    ]
